SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 15
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN_SECONDS = 0.3
SHOT_LIFETIME_SECONDS = 1.2

PLAYER_ACCELERATION = 300      # pixels/sec^2 of thrust
PLAYER_MAX_SPEED = 400
PLAYER_DRAG = 0.6   

WAVE_BASE_CONCURRENT = 4      
WAVE_BASE_QUOTA = 8            
WAVE_CONCURRENT_GROWTH = 2    
WAVE_QUOTA_GROWTH = 4         
ASTEROID_SPAWN_INTERVAL = 0.5 

POWERUP_RADIUS = 12
POWERUP_DROP_CHANCE = 0.25       
POWERUP_LIFETIME_SECONDS = 8.0   
POWERUP_DRIFT_SPEED = 30

FIRE_RATE_BUFF_DURATION = 8.0
FIRE_RATE_BUFF_MULTIPLIER = 0.4   