SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 15
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN_SECONDS = 0.3
SHOT_LIFETIME_SECONDS = 1.2

PLAYER_ACCELERATION = 300      # pixels/sec^2 of thrust
PLAYER_MAX_SPEED = 400
PLAYER_DRAG = 0.6   

DIFFICULTY_BASE_CONCURRENT = 8      
DIFFICULTY_CONCURRENT_PER_MIN = 6   
DIFFICULTY_SPEED_PER_MIN = 0.25     
ASTEROID_SPAWN_INTERVAL = 0.4 

POWERUP_RADIUS = 12
POWERUP_DROP_CHANCE = 0.25       
POWERUP_LIFETIME_SECONDS = 8.0   
POWERUP_DRIFT_SPEED = 30

FIRE_RATE_BUFF_DURATION = 8.0
FIRE_RATE_BUFF_MULTIPLIER = 0.4   

WEAPON_BUFF_DURATION = 20.0

SHOT_LIFETIME_SECONDS = 1.2      

SHOTGUN_PELLETS = 5
SHOTGUN_SPREAD = 45              
SHOTGUN_LIFETIME = 0.6         
SHOTGUN_COOLDOWN = 0.5

DOUBLE_OFFSET = 12              
DOUBLE_LIFETIME = 2.5          
DOUBLE_COOLDOWN = 0.35

MAX_BOMBS = 3
